<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Share your knowladge</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>Share your knowladge</b>
    </div>
    <div id="header-navigation" style="float: right">
		Welcome <?php echo $this->username?> <?php if ($this->username) { ?>| <a href="<?php echo $this->url(
	    array(
	        'controller' => 'auth',
	        'action'     => 'logout'
	    ),
	    'default',
	    true) ?>">logout</a> <?php } ?>
	</div>
</div>
<?php if ($this->username) { ?>
<div style="float: left">
<?php 
echo $this -> partial('sidebar.phtml'); //,array('menuitems' => $data)
?>
</div>
<?php } ?>

<?php echo $this->layout()->content ?>

</body>
</html>
